name: Build with pandoc

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v2
      - name: install pandoc
        run: wget https://github.com/jgm/pandoc/releases/download/2.13/pandoc-2.13-1-amd64.deb && sudo dpkg -i pandoc-2.13-1-amd64.deb
      - name: build the docs
        run: make
      - uses: EndBug/add-and-commit@v7
        with:
          add: "docs"
          author_name: ff6347Bot
          author_email: dev@ff6347.email
